### ISSUE TITLE
Zips upon file opening

### ISSUE THREAD

**Issue by ShoelaceMan** [sts10/vim-zipper#1]
Not sure if this is an issue or a feature, but when you first open a file, it folds everything, it'd be nice to at least have an option to disable this behavior.

**Comment by sts10** [comment]
Hey thanks for filing an issue. What `foldmethod` do you use? Manual? Syntax? (If you don't know just run `:set foldmethod`). The reason I ask is that I use `foldmethod=indent` and when I open a file the plugin doesn't fold everything. 

In any event I think I can fix your bug if I remove the `set foldenable` line in the plugin. I'm actually not 100% sure what that line does...

**Comment by ShoelaceMan** [comment]
I tried with both syntax, and indent fold methods, on vim 7.4 OSX. I deleted `set foldenable` but it didn't change anything.

EDIT: So I tracked down the source of the issue. In .vimrc, `foldlevelstart=` needs to be edited to a higher number. `foldlevelstart=1` will fold everything up to the first "foldable" area, where `foldlevelstart=2` will fold everything up to the second, and so on.

**Comment by sts10** [comment]
Ah, interesting. Glad you caught it. Sounds like I shouldn't make any changes to the plugin itself though, yeah?

**Comment by ShoelaceMan** [comment]
That is correct, this was an error from using OSX's default folding configuration.

**Comment by sts10** [comment]
Gotcha.

I hope you're enjoying the plugin! So cool that others are using it.
